<%@ Page Title="" Language="C#" MasterPageFile="~/Masters/Main.Master" AutoEventWireup="true" CodeBehind="ShoppingCart.aspx.cs" Inherits="SGShoesFinal.Masters.ShoppingCart" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <h1>Cart Contents</h1>
    <asp:LinkButton ID="lbShopMore" PostBackUrl="~/PagesPublic/BrowseProducts.aspx" CssClass="pull-right" runat="server">Continue Shopping</asp:LinkButton>
    <asp:GridView ID="gvCartContents" runat="server" CssClass="table" EmptyDataText="Your shopping cart is empty." AutoGenerateColumns="False" DataSourceID="odsCart" AutoGenerateDeleteButton="True">
        <Columns>
            <asp:BoundField DataField="ProductId" HeaderText="ProductId" SortExpression="ProductId" />
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
            <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />
            <asp:BoundField DataField="Quantity" HeaderText="Quantity" SortExpression="Quantity" />
            <asp:BoundField DataField="Total" HeaderText="Total" ReadOnly="True" SortExpression="Total" />
        </Columns>
    </asp:GridView>
    <asp:Button ID="btnCheckOut" CssClass="btn pull-right" runat="server" Text="Check Out" />
    <asp:ObjectDataSource ID="OdsCart" runat="server" DataObjectTypeName="SGShoesFinal.App_Code.CartItem" DeleteMethod="deleteCartItem" SelectMethod="getCartContents" TypeName="SGShoesFinal.App_Code.BusinessLogic" ></asp:ObjectDataSource>
</asp:Content>
